### ISSUE TITLE
LinuxChix Meetup 20th August 2017

### ISSUE THREAD

**Issue by ghost** [ILUGD/Suggestions#1]
Hello,

I immensely enjoyed the LinuxChix meetup yesterday though I did have one issue to raise.

First, let me thank the organizers, the speakers and everyone who took the time to attend the meetup for all of their hard work in making this meetup possible. It is through your dedication and effort that FOSS can gain better recognition and usage in India. Thank you!

Thank you Brihi Joshi & Shravika Mittal for the enlightening talk on Tessel. I found it quite interesting and would like to discuss the security aspects of running the Tessel board as an IOT device at some point in the future! :+1: 

आधोक्षज मिश्रा, आपकी टॉक सुनकर हमे बहुत मज़ा आया अौर हमने काफी कुछ सीखा । धन्यवाद !

Thank you to the ILUGD members for giving sharing their knowledge about i3m, I look forward to trying it one day :D

---

The issue I wanted to raise relates to one member, whose name I do not know nor do I care enough to find out, who behaved in a rude, condescending and disrespectful manner towards me when I merely tried to answer another attendee's question about [ZipBombs](https://en.wikipedia.org/wiki/Zipbomb). I believe this individual knows who he is. 

I have zero tolerance for such garbage behavior or such disrespectful individuals.

I request that should this individual and his posse be present at any future LinuxChix/ILUGD/etc meetup that they refrain from interacting with me entirely. I have no desire whatsoever to communicate with any of them in any way, shape or form.

---

Thank you for your time and for making the effort to ensure that the Indian FOSS community is a welcoming & inclusive space for everyone.

मानस

**Comment by sourabhtk37** [comment]
Although I came a bit late at the meet and missed this exchange, thanks for taking the time putting this suggestion, this shows genuine interest in the community and people at this community surely encourage this.
That said, I personally cannot judge without hearing the above mentioned party's perspective, but let's hear views of other people in the community regarding this.

**Comment by rajudev** [comment]
@manasb Thanks for giving us a review of our presence at the LinuxChix Meetup. I am happy that you had a good time, barring an incident that you had with someone. 
With that said, I hope you would understand that our meetups are an inclusive space for people having different set of opinions and views on many issues. Also each of them has an individual personality of there own. I am very concerned that you had a not so pleasant experience with a person at the meet. 
But I hope you would understand that you and I and us needs to be as inclusive as we can to accommodate people of all opinions and co-existing together. 
I am very happy that you stated your opinions here. Hoping to meet you at any of our next meetups very soon.
